account/urls.py
from django.urls import path
from .views import login_view, logout_view

app_name = 'account'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
]

blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('<slug:slug>', PostDetailView.as_view(), name='detail'),
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import contact

app_name = 'home'
urlpatterns = [
    path('', TemplateView.as_view(template_name = 'home/index.html'), name = 'index'),
    path('contact', contact, name = 'contact'),
    path('about', TemplateView.as_view(template_name = 'home/about.html'), name = 'about'),
]

miiapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/', include('blog.urls', namespace='blog')),
    path('uploader/', include('uploader.urls', namespace='uploader')),
    path('summernote/', include('django_summernote.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uploader/urls.py
from django.urls import path
from .views import index

app_name = 'uploader'
urlpatterns = [
    path('', index, name='index'),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
# from enum import unique
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.

STATUS_CHOICE = (
    (0, 'DRAFT'),
    (1, 'PUBLISHED')
)

class Post(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.URLField(blank=True)
    author = models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    excerpt = models.TextField(null=True)
    status = models.IntegerField(choices=STATUS_CHOICE, default=0)
    tags = TaggableManager()
    content = models.TextField()
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

home/models.py
from django.db import models
from django.contrib import admin
#from django_quill.fields import QuillField
# Create your models here.

class ContactMessage(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, blank=True)
    title = models.CharField(max_length=255, unique=True)
    message = models.TextField()

uploader/models.py
import os, uuid, datetime
from django.db import models
from django_summernote.models import AbstractAttachment
from django_summernote.utils import get_attachment_storage

def upload_to(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext) # 
    today = datetime.datetime.now().strftime('%d-%m-%Y')
    return os.path.join('attachments', today, filename)

# Create your models here.
class Attachment(AbstractAttachment):
    file = models.FileField(
        upload_to=upload_to,
        storage=get_attachment_storage()
    )
 

account/forms.py
from django import forms
 
class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=255)
    

home/forms.py
from django.db.models.base import Model
from django.forms import ModelForm, widgets
from .models import ContactMessage

class ContactMessageForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ('name', 'email', 'title', 'message')

uploader/forms.py
from django.forms import ModelForm
from .models import Attachment

class AttachmentForm(ModelForm):
    class Meta:
        model = Attachment
        fields = ('name', 'file')
        

account/views.py
from django.forms.forms import Form
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login, logout

from .forms import LoginForm

# Create your views here.
def login_view(request):
    if request.GET.get('next'):
        next = request.GET.get('next')
    elif 'next' in request.POST:
        next = request.POST['next']
    else: 
        next = '/'

    if request.user.is_authenticated:
        form = None
        status = 'login_logged'
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username = username, password = password)
            if user is not None:
                status = 'login_successed'
                auth_login(request, user)
            else:
                status = 'login_failed'
                form = LoginForm()
    else:
        status = 'login_'
        form = LoginForm()
    return render(request, template_name='account/login.html', context= { 
        'form': form, 
        'status': status, 
        'next': next 
    })

def logout_view(request):
    if request.GET.get('next'):
        next = request.GET.get('next')
    else: 
        next = '/'

    if not request.user.is_authenticated:
        status = 'logout_user_do_not_login'
    else:
        logout(request)
        status = 'logout_successed'
    return render(request, template_name='account/logout.html', context = {
        'next': next,
        'status': status
    })

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post

# Create your views here.
class PostListView(ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/index.html'
    paginate_by = 10

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'

home/views.py
from django.shortcuts import render
from .forms import ContactMessageForm

# Create your views here.
def contact(request):
    if request.method == 'POST':
        form = ContactMessageForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
            status = 'form_saved'
        else:
            status = 'form_invalid'
    else:
        form = ContactMessageForm()
        status = 'form_nodata'

    return render(request, 'home/contact.html', { 'form': form, 'status': status, 'title': 'MiiApp - Contact me!' })

uploader/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import AttachmentForm
from .models import Attachment

# Create your views here.
@login_required(login_url='/admin/login/')
def index(request):
    if request.method=='POST':
        form = AttachmentForm(request.POST, request.FILES)
        if form.is_valid():
            print(form)
            form.save()
            status = 'file_saved'
        else:
            status = 'file_invalid'
    else:
        form = AttachmentForm()
        status = 'file_selectting'
    docs = Attachment.objects.order_by('-uploaded').all()
    page_number = request.GET.get('page')
    paginator = Paginator(docs, 10)
    page_obj = paginator.get_page(page_number)
    return render(request, 'uploader/index.html', {
        'form': form,
        'status': status,
        'title': 'MiiApp - Uploader',
        'page_obj': page_obj
    })

# class AttachmentListView(ListView):
#     model = Attachment
#     paginate_by = 2
#     template_name = 'uploader/files'

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block 'content' %}
    {% include 'navbar.html' %}
    <div class="container-fluid mt-3" style="max-width:1200px">
        <div class="row">
            <div class="col-lg-8">
                <div class="card post-detail mb-3">
                    <div class="card-body">
                        {% if post %}
                        <h3>{{ post.title }}</h3>
                            <span class="text-muted">Author: {{ post.author }}. Created on: {{ post.created_on | date:'m-d-Y h:i A'}} <br/></span>
                            <div class="post-list-excerpt mb-3 mt-3">
                                {{ post.content|safe }}
                            </div>
                        {% else %}
                            <div class="alert alert-danger">
                                Post not found ...!
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                Widgets
            </div>
        </div>
    </div>
{% endblock %}

{% block 'style' %}
    {% render_bundle 'main' 'css' %}
    <link rel="stylesheet" href="{% static 'katex/katex.min.css'%}">
{% endblock %}

{% block 'scripts' %}
    {% render_bundle 'main' 'js' %}
    <script src="{% static 'katex/katex.min.js'%}"></script>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block 'content' %}
    {% include 'navbar.html' %}
    <div class="container-fluid mt-3" style="max-width:1200px">
        <div class="row">
            <div class="col-lg-8">
            {% if page_obj %}
                {% for post in page_obj %}
                    <div class="card mb-3 post-list-item">
                        <div class="card-body row">
                            <div class="col-md-12 mb-3">
                                <h3>{{ post.title }}</h3>
                                <span class="text-muted">Author: {{ post.author }}. Created on: {{ post.created_on | date:'m-d-Y h:i A'}} <br/></span>
                            </div>
                            <div class="col-md-4 " style="overflow:hidden">
                                <img src="{% firstof post.image 'https://dummyimage.com/600x400/000/fff' %}" alt="{{post.title}}" class="post-list-image"/>
                            </div>
                            <div class="col-md-8">
                                <div class="post-list-excerpt mb-3">
                                    {% firstof post.excerpt|safe post.content|safe %}
                                </div>
                                <a href="{% url 'blog:detail' post.slug %}" class="btn btn-primary post-list-title">Readmore...</a><br/>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% include 'blog/paginator.html' %}
            {% else %}
                <div class="card mb-3 post-list-item">
                    <div class="card-body">
                        <div class="alert alert-danger">
                            There is no post here ..!
                        </div>
                    </div>
                </div>
            {% endif %}
            </div>
            <div class="col-lg-4">
                Widgets
            </div>
        </div>
    </div>
{% endblock %}

{% block 'style' %}
    {% render_bundle 'main' 'css' %}
    <link rel="stylesheet" href="{% static 'katex/katex.min.css'%}">
{% endblock %}

{% block 'scripts' %}
    {% render_bundle 'main' 'js' %}
    <script src="{% static 'katex/katex.min.js'%}"></script>
{% endblock %}

blog/templates/blog/paginator.html
<ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
    {% endif %}
        
    <li class="page-item disabled">
        <a class="page-link" href="#" >Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
    </li>
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" tabindex="-1" aria-disabled="true">Next</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
        </li>
    {% endif %}
</ul>

home/templates/home/about.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block 'content' %}
    {% include 'navbar.html' %}
    <div class="container-fluid" style="max-width:1200px">
        About me !
    </div>
{% endblock %}

{% block 'style' %}
    {% render_bundle 'main' 'css' %}
{% endblock %}

{% block 'scripts' %}
    {% render_bundle 'main' 'js' %}
{% endblock %}

home/templates/home/contact.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load render_bundle from webpack_loader %}

{% block 'content' %}
    {% include 'navbar.html' %}
    <div class="container mt-3" style="max-width:1200px">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header text-center">
                        <b>Contact me</b>
                    </div>
                    <div class="card-body">
                        {% if status == 'form_saved' %}
                        <div class="alert alert-success mb-3">
                            Message is submitted, thanks for your feedback!
                        </div>
                        {% endif %}
                        {% if status == 'form_invalid' %}
                        <div class="alert alert-danger mb-3">
                            There is error while submitting message, please check again!
                        </div>
                        {% endif %}
                        <form action="{% url 'home:contact' %}" method="POST" enctype="multipart/form-data" class="row">
                            <div class="col-md-6">
                                <div class="input-group mb-3">
                                    <span class="input-group-text" style="width: 80px;">Name:</span>
                                    {% render_field form.name class="form-control" placeholder="Enter your name" %}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="input-group mb-3">
                                    <span class="input-group-text" style="width: 80px;">Email:</span>
                                    {% render_field form.email class="form-control" placeholder="Enter your email" %}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="mb-3">
                                    <label for="title">Title:</label>
                                    {% render_field form.title class="form-control" placeholder="Enter the title of the message" %}
                                </div>
                                <div class="mb-3">
                                    <label for="title" class="form-label">Message: </label>
                                    {% render_field form.message class="form-control" placeholder="Enter the message here" %}  
                                </div>      
                                <div class="mt-3">
                                    {% csrf_token %}
                                    <input type="submit" value="Submit" class="btn btn-primary"/>
                                    <input type="reset" value="Reset" class="btn btn-danger"/>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
        </div>
        </div>     
    </div>
{% endblock %}

{% block 'style' %}
    {% render_bundle 'main' 'css' %}
{% endblock %}

{% block 'scripts' %}
    {% render_bundle 'main' 'js' %}
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block 'content' %}
    {% include 'navbar.html' %}
    <div class="container-fluid" style="max-width:1200px">
        <div class="row">
            <div class="col-lg-8">
                COntainer
            </div>
            <div class="col-lg-4">
                Widgets
            </div>
        </div>
    </div>
{% endblock %}

{% block 'style' %}
    {% render_bundle 'main' 'css' %}
{% endblock %}

{% block 'scripts' %}
    {% render_bundle 'main' 'js' %}
{% endblock %}

miiapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    {% block 'style' %}{% endblock %}
    <title>{% firstof title "Mii Application framework by HuynhAT"%}</title>
</head>
<body>
    {% block 'content' %}{% endblock %}
    {% block 'scripts' %}{% endblock %}
    
</body>
</html>

miiapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid" style="max-width:1200px">
        <a class="navbar-brand" href="{% url 'home:index' %}">
            {% comment %} <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="d-block my-1" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg> {% endcomment %}
            LineBlog
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
                </li>
                {% comment %} <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a> {% endcomment %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'uploader:index' %}">Uploader</a>
                </li>
               
            </ul>
            <ul class="navbar-nav d-flex">
                <li class="nav-item dropdown">
                    {% comment %} <a class="nav-link" href="{% url 'home:about' %}" style="display:inline-block;padding-right:0px;">About</a>
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" style="display:inline-block;padding-left:0px;" data-bs-toggle="dropdown" aria-expanded="false">
                        <b class="caret"></b>
                    </a> {% endcomment %}
                    <a class="nav-link dropdown-toggle" href="{% url 'home:about' %}" data-bs-toggle="dropdown"  id="aboutToggler">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                          <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                        </svg>
                    </a>
                    <ul class="dropdown-menu" id = "aboutDropdownMenu" aria-labelledby="aboutToggler">
                        {% if user.is_authenticated %}
                            {%if user.is_staff or user.is_supperuser %}
                            <li>
                                <a class="nav-link dropdown-item" href="{% url 'admin:index' %}">Admin page</a>
                            </li>
                            {% endif %}
                            <li>
                                <a class="nav-link dropdown-item" href="{% url 'account:logout' %}?next={{ request.get_full_path }}">Logout</a>
                            </li>
                        {% else %}
                            <li>
                                <a class="nav-link dropdown-item" href="{% url 'account:login' %}?next={{ request.get_full_path }}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
                 <li class="nav-item dropdown me-2">
                    {% comment %} <a class="nav-link" href="{% url 'home:about' %}" style="display:inline-block;padding-right:0px;">About</a>
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" style="display:inline-block;padding-left:0px;" data-bs-toggle="dropdown" aria-expanded="false">
                        <b class="caret"></b>
                    </a> {% endcomment %}
                    <a class="nav-link dropdown-toggle" href="{% url 'home:about' %}" data-bs-toggle="dropdown"  id="aboutToggler">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-question-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
                        </svg>
                    </a>
                    <ul class="dropdown-menu" id = "aboutDropdownMenu" aria-labelledby="aboutToggler">
                        <li><a class="nav-link dropdown-item" href="{% url 'home:about' %}" >About.</a></li>
                        <li><a class="nav-link dropdown-item" href="{% url 'home:contact' %}">Contact me!</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>  

uploader/templates/uploader/index.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% load widget_tweaks %}
{% load filename %}
{% block 'content' %}
    {% include 'navbar.html' %}
    <div class="container-fluid mt-3" style="max-width:1200px;">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center" style="margin-top: -1px">
                    <b>MiiApp - Uploader</b>
                </div>
                <div class="card-body">
                    {% if status == 'file_saved' %}
                        <div class="alert alert-success">File Uploaded ...!</div>
                    {% endif %}
                    {% if status == 'file_invalid' %}
                        <div class="alert alert-danger">Upload file failed ...!</div>
                    {% endif %}
                    <form action="{% url 'uploader:index' %}" method="POST" enctype="multipart/form-data">
                        <div class="input-group mb-3">
                            {% render_field form.file class="form-control" id="inputGroupFile01" style="margin-left: 1px;"%}
                            </div>
                        <div class="input-group mb-3">
                            <label for="id_name" class="input-group-text">Name: </label>
                            {% render_field form.name class="form-control" %}
                        </div>
                        <div class="mb-3">
                            {% csrf_token %}
                            <input type="submit" value="Upload" class="btn btn-primary" />
                            <input type="reset" value="Reset" class="btn btn-danger" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <b>Files uploaded:</b>
                </div>
                <ul class="list-group list-group-flush file-list">
                    {% for doc in page_obj %}
                    <li class="list-group-item">
                        <a href="{{ doc.file.url }}" target="_blank">{% firstof doc.name doc.file.name|filename %}</a>
                    </li>
                    {% endfor %}
                    <li class="list-group-item">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                                </li>
                            {% endif %}
                                
                            <li class="page-item disabled">
                                <a class="page-link" href="#" >Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                            </li>
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" tabindex="-1" aria-disabled="true">Next</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
                
            </div>
        </div>
    </div>

    </div>
{% endblock %}

{% block 'style' %}
    {% render_bundle 'main' 'css' %}
{% endblock %}

{% block 'scripts' %}
    {% render_bundle 'main' 'js' %}
{% endblock %}